apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  SPRING_DATA_MONGODB_URI: "mongodb://fiap@GpP36_Fiap2024!:27017/restaurant"
  RABBIT_HOST: "fiap"
  RABBIT_PASSWORD: "GpP36_Fiap2024!"
