apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-payment
  template:
    metadata:
      name: pod-payment
      labels:
        app: pod-payment
    spec:
      containers:
        - name: api-payment-container
          image: kaique98/api-payment-group-36:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://usuario:senha@<ENDPOINT_MONGO>:27017/restaurant"
            - name: RABBIT_HOST
              value: "af4b45659baf047e49724279ab7d29eb.amazonaws.com"
            - name: RABBIT_USER
              value: "fiap"
            - name: RABBIT_PASSWORD
              value: "GpP36_Fiap@2024!"
          envFrom:
            - configMapRef:
                name: api-configmap
          livenessProbe:
            httpGet:
              port: 8080
              path: /payment/actuator/health/liveness
            periodSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              port: 8080
              path: /payment/actuator/health/readiness
            periodSeconds: 5
            failureThreshold: 3
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 200m
      volumes: []  # Removendo volume para RabbitMQ, se não necessário
